#!/bin/bash -l
#SBATCH --qos=xfer
#SBATCH --time=48:00:00
#SBATCH --job-name=garden_to_hpss
#SBATCH --licenses=SCRATCH
#SBATCH --mail-user=phuck@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH --output=garden_to_hpss-%j.out
#SBATCH --error=garden_to_hpss-%j.error

script=$HOME/mp_prod/codes/emmet/emmet/scripts/garden_to_hpss.sh
#indir=/project/projectdirs/matgen/garden/MatProj
#indir=/project/projectdirs/matgen/garden/garden_to_hpss

#indir=/project/projectdirs/matgen/basf/original # TODO
indir=/global/projecta/projectdirs/matgen/hling/nmr_old/Si
#indir=/global/projecta/projectdirs/matgen/hling/nmr_old/Al
filter="block_*"

$script $indir $filter
