#!/bin/bash -l
#SBATCH --qos=xfer
#SBATCH --time=48:00:00
#SBATCH --job-name=restore
#SBATCH --licenses=SCRATCH
#SBATCH --mail-user=phuck@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH --output=restore-%j.out
#SBATCH --error=restore-%j.error

cwd=$PWD

#outdir=/global/cscratch1/sd/huck/tasks_from_old_prod_2019/
#dirlist="/global/homes/h/huck/mp_prod/workdir/tasks_from_old_prod_2019/restore.txt"

#outdir=/project/projectdirs/matgen/garden/jmunro/
#dirlist="/global/homes/h/huck/mp_prod/workdir/hpss/max_estep_dir.txt"

outdir=/project/projectdirs/matgen/garden/rkingsbury/
dirlist="/global/homes/h/huck/mp_prod/workdir/hpss/scan_dirs_2.txt"

cd $outdir && pwd

for block in `cut -d/ -f1 $dirlist | sort -u`; do
  echo $block
  list=""
  for l in `grep $block $dirlist`; do
    [[ ! -e $l ]] && echo "$l does not exist" && list="$list $l"
  done
  [[ ! -z "$list" ]] && echo "htar -x ..." && htar -xvf garden/${block}.tar $list
  #break
done

cd $cwd
echo DONE
