[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
only-include = ["emmet/builders"]
dev-mode-dirs = ["."]

[tool.hatch.build.targets.sdist]
include = [
  "emmet/builders",
  "tests",
  "pyproject.toml",
]

[project]
name = "emmet-builders"
dynamic = ["version"]
requires-python = ">=3.12"
description = "Builders for the Emmet Library"
authors = [
  { name = "The Materials Project", email = "feedback@materialsproject.org" },
]
license = "BSD-3-Clause-LBNL"
dependencies = [
  "emmet-core[all]>=0.87.3rc",
  "pymatgen>=2026.9.24",
]

[project.urls]
Homepage = "https://github.com/materialsproject/emmet/tree/main/emmet-builders/"
Documentation = "https://materialsproject.github.io/emmet/"

[project.optional-dependencies]
test = [
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pytest-xdist",
  "pycodestyle",
  "pydocstyle",
  "flake8",
  "mypy",
  "mypy-extensions",
]
docs = [
  "mkdocs",
  "mkdocs-material<8.3",
  "mkdocs-material-extensions",
  "mkdocs-minify-plugin",
  "mkdocstrings",
  "mkdocs-awesome-pages-plugin",
  "mkdocs-markdownextradata-plugin",
  "mkdocstrings[python]",
  "livereload",
  "jinja2",
]
