from setuptools import find_namespace_packages, setup

setup(
    name="emmet-builders",
    use_scm_version={"root": "..", "relative_to": __file__},
    setup_requires=["setuptools_scm"],
    description="Builders for the Emmet Library",
    author="The Materials Project",
    author_email="feedback@materialsproject.org",
    url="https://github.com/materialsproject/emmet",
    packages=find_namespace_packages(include=["emmet.*"]),
    install_requires=["emmet-core[all]", "maggma>=0.49.9", "matminer>=0.7.3"],
    extras_require={
        "test": [
            "pre-commit",
            "pytest",
            "pytest-cov",
            "pycodestyle",
            "pydocstyle",
            "flake8",
            "mypy",
            "mypy-extensions",
            "types-setuptools",
            "types-requests",
            "wincertstore",
            "openbabel",
        ],
        "docs": [
            "mkdocs==1.3.0",
            "mkdocs-material==8.2.11" "mkdocs-material-extensions==1.0.3",
            "mkdocs-minify-plugin==0.5.0",
            "mkdocstrings==0.18.1",
            "mkdocs-awesome-pages-plugin==2.7.0",
            "mkdocs-markdownextradata-plugin==0.2.5",
            "livereload==2.6.3" "jinja2<=3.0.0",
        ],
    },
    python_requires=">=3.8",
    license="modified BSD",
    zip_safe=False,
)
