
[tool.ruff]
target-version = "py38"
select = [
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "D",   # pydocstyle
  "E",   # pycodestyle error
  "EXE", # flake8-executable
  "F",   # pyflakes
  "FLY", # flynt
  "I",   # isort
  "ICN", # flake8-import-conventions
  "ISC", # flake8-implicit-str-concat
  "N",   # pep8-naming
  "PD",  # pandas-vet
  "PIE", # flake8-pie
  "PL",  # pylint
  "PT",  # flake8-pytest-style
  "PYI", # flakes8-pyi
  "Q",   # flake8-quotes
  "RET", # flake8-return
  "RSE", # flake8-raise
  "RUF", # Ruff-specific rules
  "SIM", # flake8-simplify
  "TID", # tidy imports
  "UP",  # pyupgrade
  "W",   # pycodestyle warning
  "YTT", # flake8-2020
]
ignore = [
  "C408",    # unnecessary-collection-call
  "D100",    # undocumented-public-module
  "D205",    # blank-line-after-summary
  "E731",    # lambda-assignment
  "N806",    # non-lowercase-variable-in-function
  "PD901",   # pandas-df-variable-name
  "PLC0414", # useless-import-alias
  "PLC1901", # compare-to-empty-string
  "PLR",     # pylint refactor
  "PLW2901", # redefined-loop-name
  "PT006",   # pytest-parametrize-names-wrong-type
  "PT011",   # pytest-raises-too-broad
  "PT013",   # pytest-incorrect-pytest-import
]
pydocstyle.convention = "google"
