"""
Autogenerated Enums for CP2K RunType, TaskType, and CalcType
Do not edit this by hand. Edit generate.py or run_types.yaml instead
"""
from emmet.core.utils import ValueEnum


class RunType(ValueEnum):
    """ CP2K calculation run types """

    PBE = "PBE"
    GGA = "GGA"
    HYBRID = "HYBRID"
    HSE06 = "HSE06"
    PB0 = "PB0"
    RSH = "RSH"
    PBE_U = "PBE+U"
    GGA_U = "GGA+U"
    HYBRID_U = "HYBRID+U"
    HSE06_U = "HSE06+U"
    PB0_U = "PB0+U"
    RSH_U = "RSH+U"
    LDA = "LDA"
    LDA_U = "LDA+U"


class TaskType(ValueEnum):
    """ CP2K calculation task types """

    Static = "Static"
    Structure_Optimization = "Structure Optimization"


class CalcType(ValueEnum):
    """ CP2K calculation types """

    PBE_Static = "PBE Static"
    PBE_Structure_Optimization = "PBE Structure Optimization"
    GGA_Static = "GGA Static"
    GGA_Structure_Optimization = "GGA Structure Optimization"
    HYBRID_Static = "HYBRID Static"
    HYBRID_Structure_Optimization = "HYBRID Structure Optimization"
    HSE06_Static = "HSE06 Static"
    HSE06_Structure_Optimization = "HSE06 Structure Optimization"
    PB0_Static = "PB0 Static"
    PB0_Structure_Optimization = "PB0 Structure Optimization"
    RSH_Static = "RSH Static"
    RSH_Structure_Optimization = "RSH Structure Optimization"
    PBE_U_Static = "PBE+U Static"
    PBE_U_Structure_Optimization = "PBE+U Structure Optimization"
    GGA_U_Static = "GGA+U Static"
    GGA_U_Structure_Optimization = "GGA+U Structure Optimization"
    HYBRID_U_Static = "HYBRID+U Static"
    HYBRID_U_Structure_Optimization = "HYBRID+U Structure Optimization"
    HSE06_U_Static = "HSE06+U Static"
    HSE06_U_Structure_Optimization = "HSE06+U Structure Optimization"
    PB0_U_Static = "PB0+U Static"
    PB0_U_Structure_Optimization = "PB0+U Structure Optimization"
    RSH_U_Static = "RSH+U Static"
    RSH_U_Structure_Optimization = "RSH+U Structure Optimization"
    LDA_Static = "LDA Static"
    LDA_Structure_Optimization = "LDA Structure Optimization"
    LDA_U_Static = "LDA+U Static"
    LDA_U_Structure_Optimization = "LDA+U Structure Optimization"
