[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
only-include = ["emmet/core"]
dev-mode-dirs = ["."]

[tool.hatch.build.targets.sdist]
include = [
  "emmet/core",
  "tests",
  "pyproject.toml",
]

[project]
name = "emmet-core"
dynamic = ["version"]
requires-python = ">=3.12"
description="Core Emmet Library"
license = "BSD-3-Clause-LBNL"
authors = [
    {name = "The Materials Project", email="feedback@materialsproject.org"},
]
dependencies = [
  "pymatgen",
  "pymatgen-core>=2026.7.31",
  "monty>=2024.2.2",
  "pydantic>=2.12",
  "pydantic-settings>=2.0",
  "pymatgen-io-validation>=0.1.1",
  "pybtex~=0.24",
  "typing-extensions>=3.7",
  "blake3",
  "inflect",
  "pubchempy",
]

[project.urls]
Homepage = "https://github.com/materialsproject/emmet"
Documentation = "https://materialsproject.github.io/emmet/"

[project.optional-dependencies]
all = [
  "seekpath>=2.0.1",
  "pymatgen-analysis-defects>=2024.7.18",
  "pymatgen-analysis-diffusion>=2026.9.23",
  "pymatgen-analysis-alloys>=0.0.6",
  "pyarrow",
  "pymongo",
  "pycodcif",
  "lobsterpy",
  "phonopy>=3.0.0",
]
test = [
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pytest-xdist",
  "pycodestyle",
  "pydocstyle",
  "flake8",
  "mypy",
  "mypy-extensions",
  "types-setuptools",
  "types-requests",
  "custodian",
]
docs = [
  "sphinx<9.0.0",
  "sphinx-rtd-theme>=3.0.2",
  "sphinx-markdown-builder>=0.6.8",
  "sphinx-autodoc-typehints",
  "myst-parser",
]
