name: Post-process

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'testing'

jobs:
  auto-gen-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.EMMET_SEMVER_BUMP_TOKEN }}
    steps:
      - # It is often a desired behavior to merge only when a workflow execution
        # succeeds. This can be changed as needed.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: rymndhng/release-on-push-action@v0.25.0
        with:
          bump_version_scheme: norelease
